name: Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''
          log-accepted-android-sdk-licenses: false
      - name: Cache Android SDK packages
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.ANDROID_HOME }}/platforms/android-36
            ${{ env.ANDROID_HOME }}/build-tools/36.0.0
            ${{ env.ANDROID_HOME }}/ndk/28.2.13676358
            ${{ env.ANDROID_HOME }}/cmake/3.22.1
          key: ${{ runner.os }}-${{ runner.arch }}-android-sdk-${{ hashFiles('app/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-android-sdk-
      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --build-cache assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/outputs/apk/debug/*.apk
